;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua-copy-region
	cua-cut-region
	cua-paste
	cua-set-rectangle-mark
	electric-newline-and-maybe-indent
	move-text-down
	move-text-up
	slime-autodoc-space
	slime-space
	))

(setq mc/cmds-to-run-once
      '(
	compile
	mc/mark-next-lines
	slime-compile-defun
	))
